export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_FETCHED = 'USER_FETCHED';

/* ========================== BOOK DATA ========================= */

export const FETCH_TOP_BOOK_DATA_TYPE = 'FETCH_TOP_BOOK_DATA';
export const FETCH_BOOK_DATA_TYPE = 'FETCH_BOOK_DATA';
export const FETCH_USER_BOOKS_DATA_TYPE = 'FETCH_USER_BOOKS_DATA';

/* ======================= BOOK OPERATIONS ===================== */

export const ADD_READ_BOOK_TYPE = 'ADD_READ_BOOK_OPERATIONS';
export const DELETE_READ_BOOK_TYPE = 'DELETE_READ_BOOK_OPERATIONS';

export const ADD_LIKE_BOOK_TYPE = 'ADD_LIKE_BOOK_OPERATIONS';
export const DELETE_LIKE_BOOK_TYPE = 'DELETE_LIKE_BOOK_OPERATIONS';

export const UPDATE_PROGRESS_TYPE = 'UPDATE_PROGRESS_OPERATIONS';


export const SEARCH_BOOKS_BY_PAGE_TYPE = 'SEARCH_BOOKS_BY_PAGE';
export const CHANGE_FILTERS_TYPE = 'CHANGE_FILTERS';
export const SORTING_BOOKS_TYPE = 'SORTING_BOOKS';
