export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_FETCHED = 'USER_FETCHED';


export const FETCH_TOP_TYPE = 'FETCH_TOP';
export const FETCH_BOOK_DATA_TYPE = 'FETCH_BOOK_DATA';
export const FETCH_USER_BOOKS_TYPE = 'FETCH_USER_BOOKS';
export const SEARCH_BOOKS_BY_PAGE_TYPE = 'SEARCH_BOOKS_BY_PAGE';

export const CHANGE_FILTERS_TYPE = 'CHANGE_FILTERS';
export const SORTING_BOOKS_TYPE = 'SORTING_BOOKS';

export const ADD_BOOK_TYPE = 'ADD_BOOK_FEATURE';
export const DELETE_BOOK_TYPE = 'DELETE_BOOK_FEATURE';

export const ADD_LIKE_TYPE = 'ADD_LIKE_FEATURE';
export const DELETE_LIKE_TYPE = 'DELETE_LIKE_FEATURE';

export const UPDATE_PROGRESS_TYPE = 'UPDATE_PROGRESS_FEATURE';
